# NOTES compiled from deeplizard youtube videos

# Convolutional neural networks

## Collection of technology behind deep learning
#### Math Tools: Calculus, Linear Algebra
#### CS Tools: Python, PyTorch
#### Physics/Engg Tools: CPU, GPU
#### ML Tools: Neural Networks, Layers, Activation Functions

CNNs are artificial neural nets used for image recognitiopn in deep learning.

Let's explore typical neural input shape, input channels, output channels and feature maps

1. Shape of CNN input typically has a length of 4
2. So, we have a Rank 4 tensor with 4 axis, each index in a tensor shape represents a specific axis
3. Image height and width are represented on the last two axes [?,?,H,W]
4. C, H, W -> third from the left input represents color channels(typical values are 3 for RGB
images or 1 for gray-scale images. color channel interpretation is only applicable to input tensor.
5. [?,C,H,W] -> this represents a complete image as a tensor
6. So, we need 3 indices to define an image
7. in order to axes data in this form we need 3 indices.
8. In order to arrive at a specific pixel value, we choose a color channel, then a height and a width.
9. B, C, H, W -> The first axis in the input represents batch size: how many samples are in the batch
10. Channels are the outputs from convolution layer, hence it is output channel as opposed to color channel

In [ ]:
# tensor input for CNN
# image input as a tensor to CNN
[3,1, 28,28]
#batch of 3 images, each image has a single color channel, and the image height and width are 28 x 28 respectively
# Rank 4 tensor that will flow through the comnvolutional neural network


In [ ]:
[1,1,28,28]
# when this is passed through convolutional layer, height and width changes as well as the color channel


# No of channels changes based on the no of filters used in the convolutional layer
Suppose there are 3 convolutional filters
1. 3 channel outputs from the convolutional layer
2. These channels are the outputs from the convolutional layer, hence the name output channel
3. each of the 3 filters convolves the original single input channel  producing 3 output channels

In [4]:
# output channel
[1, 3, 28, 28]
# Depending on the filter dimensions, height and width of the output will also change
# these modified color channels in the output are called feature maps.

# PyTorch Tensors

1. Instances of the torch.Tensor PyTorch class
2. Difference between abstract concept tensor and PyTorch tensor lies at the implementation level
as we can work with the code.
2. tensor contains numerical uniform data with one datatype
3. tensor datatype has a CPU and a GPU version

## Note: torch.Tensor(with upper case T): is the class constructor
### torch.tensor(with lower case t) is the factory function that builds tensor objects for us.
Factory functions are a software design pattern for creating objects.

### Factory function torch.tensor() has better documentation, so it is better to use that while creating object.


In [3]:
# PyTorch tensors: instances of the torch.Tensor class that lives in the torch package 
# data preprocessing( transform raw input data into tensor form)
import torch
import numpy as np
t = torch.Tensor()
print("type-> ",type(t))

# PyTorch tensor attributes
print("dtype-> ",t.dtype)
print("device-> ",t.device)
print("layout-> ",t.layout)
#layout: strided specifies how the tensor is stored in memory

type->  <class 'torch.Tensor'>
dtype->  torch.float32
device->  cpu
layout->  torch.strided


# Change the device to GPU

In [11]:
#device is GPU and it is the first GPU that we have
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [23]:
test = [1, 2, 3] # Python list to tensor
tt = torch.tensor(test)
type(tt)

torch.Tensor

# Create Tensors using Data

In [29]:
data = np.array([1, 2, 3]) # from numpy array
print(type(data))
# let's create tensors using with multiple options
o1 = torch.Tensor(data)
print("option 1-> ",o1, o1.dtype)
o2 = torch.tensor(data)
print("option 2-> ",o2, o2.dtype)
o3 = torch.as_tensor(data)
print("option 3-> ",o3, o3.dtype)
o4 = torch.from_numpy(data)
print("option 4-> ",o4, o4.dtype)
#Note: o1 produces float, rest are integers

<class 'numpy.ndarray'>
option 1->  tensor([1., 2., 3.]) torch.float32
option 2->  tensor([1, 2, 3]) torch.int64
option 3->  tensor([1, 2, 3]) torch.int64
option 4->  tensor([1, 2, 3]) torch.int64


In [27]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1., 2., 3.])
t1.dtype, t2.dtype

(torch.int64, torch.float32)

# Create Tensors without Data

In [9]:
# 2-D tensors with ones on the diagonal, zeros elsewhere
print(torch.eye(2))
# tensors with zeroes of given shape
print(torch.zeros([2,2]))
# tensors with ones of given shape
print(torch.ones([2,2]))
# tensors with random numbers of given shape
print(torch.rand([2,2]))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.7413, 0.4015],
        [0.7155, 0.7526]])


In [30]:
# default dtype
torch.get_default_dtype()

torch.float32

In [25]:
o1.dtype, o2.dtype, o3.dtype, o4.dtype

(torch.float32, torch.int64, torch.int64, torch.int64)

In [31]:
# torch.Tensor() constructor uses default dtype when building tensor
# other calls chose dtype based on the type of the incoming data ( type inference)
o1.dtype == torch.get_default_dtype()

True

In [34]:
# while using torch.tensor() factory class, we can pass dtype explicitly, whereas torch.Tensor() constructor
# class does not allow that
torch.tensor(data, dtype = torch.float32)
torch.as_tensor(data, dtype=torch.float32)

tensor([1., 2., 3.])

# Sharing memory for performance vs Copy

1. tortch.Tensor() and torch.tensor() copy input data
2. torch.as_tensor() and torch.from_numpy() share input data in memory with original input object

In [36]:
print('old:', data)
data[0] = 0
print('new:', data)

old: [1 2 3]
new: [0 2 3]


In [38]:
o1, o2, o3, o4 # o1, o2 are unchanged whereas o2 and o3 took new input data

(tensor([1., 2., 3.]), tensor([1, 2, 3]), tensor([0, 2, 3]), tensor([0, 2, 3]))

In [41]:
# convert torch.tensor() to numpy.ndarray
o3.numpy(), o4.numpy(), o1.numpy(), o2.numpy()

(array([0, 2, 3]),
 array([0, 2, 3]),
 array([1., 2., 3.], dtype=float32),
 array([1, 2, 3]))

In [42]:
type(o3.numpy()), type(o4.numpy()), type(o1.numpy()), type(o2.numpy())

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Best Options For Creating Tensors in PyTorch

1. torch.tensor()
2. totch.as_tensor() # torch.from_numpy() is restricted as it only accepts numpy.ndarray 

# Numpy bridge
## zero memory-copy very efficient

In [45]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [46]:
b = a.numpy
print(b)

<built-in method numpy of Tensor object at 0x128c8d990>


# Things to remember

1. numpy.ndarray objects are allocated on CPU, as_tensor() function must copy data from CPU to GPU, when GPU is used
2. memory sharing of as_tensor() doesn't work with built-in Pythion data structure, like list.
3. as_tensor() call requires developer's knowledge'
4. as_tensor()perfortmance improvement will be greater if lot of back and forth between numpy.ndarray and tensor objects