# NOTES compiled from deeplizard youtube videos

### Tensor operations for neural networks and deep learning

4 high level operations
1. Reshaping
2. Element-wise
3. Reduiction
4. Access

Neural network: 
1. Maps input data to the cortrect output
2. tensor is the data structure that is efficiently implemented into code to use the abstract concept data.


# Tensor Shape

In [4]:
import torch
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
], dtype=torch.float32)
t, t.size(), t.shape, len(t.shape) # obtain the rank by taking the length of a shape
# it's a 3x4 rank 2 tensor with 2 axes, first axes has a length of 3 and 2nd axes has a length of 4
# elements of first axes are array and elements of 2nd axes are numbers
# rank is the number of dimensions present within this tensor
# rank is the length  of the tensor's shape
# PyTorch size and shape mean the same thing

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]), torch.Size([3, 4]), torch.Size([3, 4]), 2)

# Tensor Reshaping
# ( without changing the rank)

1. Reshaping accounts for the number of elements present
2. Reshaping changes the tensor's shape but not the underlying data

### Squeezing : removes dimensions or  axes that have length 1 # expand therank of a tensor
### Unsqueezing: adds a dimension with a length of 1 # shrink the rank of a tensor

In [14]:
# number of elements inside a tensor
torch.tensor(t.shape).prod(), t.numel()
# row* columns = number of elements
# scalar components of the tensor

(tensor(12), 12)

In [17]:
t.reshape([1,12]), t.reshape([1,12]).shape, t.reshape([1,12]).squeeze(), t.reshape([1,12]).squeeze().shape

(tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]),
 torch.Size([1, 12]),
 tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]),
 torch.Size([12]))

In [20]:
t.reshape([1,12]).squeeze().unsqueeze(dim=0)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [21]:
t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape

torch.Size([1, 12])

In [9]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [10]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [11]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [12]:
t.reshape([6,2])

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [13]:
t.reshape([12, 1])

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [15]:
t.reshape([2,2,3]) # rank 3 tensor

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

# Flatten operation

1. Flatten operations are required when passing an output tensor from a convolutional layer to a linear layer
2. This is because, convolutional layer outputs that are passed to a fully connected layer muct be flattened
out before the fully connected layer accepts the input.
3. Suppose a tensor t=[2, 1, 28, 28] for CNN that represents a batch of 2 grayscale images with height and width dimensions of 28x28.
4. We can flatten 2 images to get the shape [2, 1, 784]
5. We can squeeze off the channel axes to get the shape[2, 784]
5. Flattening a tensor converts a tensor into a lower dimensional tenmsor

In [28]:
def flatten(t): # takes a tensor argument
    t = t.reshape(1, -1) # since tensor argument can be of any shape, we pass a -1 for the 2nd argument of
                        # the reshape function 
    t = t.squeeze()
    return t
t = torch.ones(4,3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
t.reshape(1, 12)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Concatenating tensors

In [26]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])
t2 = torch.tensor([
    [5, 6],
    [7,8]
])
torch.cat((t1, t2), dim=0), torch.cat((t1, t2), dim=0).shape # combine t1 & t2 row wise(axis-0)

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]), torch.Size([4, 2]))

In [27]:
torch.cat((t1, t2), dim=1), torch.cat((t1, t2), dim=1).shape # combine t1 and t2 column wise(axis-1)

(tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]), torch.Size([2, 4]))

# Flattening Specific axes of a tensor
## Building tensor representation of a batch of images
### In order to flatten a tensor we need atleast two axes.

tensor input to a convolutional neural net(CNN) has 4 axes(Batch Size, Color Channel, Height, Width).
1. Let's consider 3 images of shape 4x4, so 3 rank-2 tensors
2. Batches are represented using a single tensor, hence these 3 tensors need to be combined to a single larger tensor with 3 axes instead of 2.
3. use stack() to concatenate the sequence of 3 tensors along a new axis.
4. since 3 tensors along a new axis, length of that new axis =3

In [32]:
t1 = torch.tensor([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])
t2 = torch.tensor([
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2]
])
t3 = torch.tensor([
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3]
])
t = torch.stack((t1, t2, t3))
t.shape, t # axis of length 3 represents batch size
           # axis of length 4 represents height and width
           # this is a rank-3 tensor that contains a batch of 3 4x4 images
           # CNN expects an implicit single color channel for each of these 3 image tensors
           # so this would be grayscale images

(torch.Size([3, 4, 4]), tensor([[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]],
 
         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],
 
         [[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]))

In [33]:
# For CNN, let's add an explicit color channel axis by reshaping the tensor
# additional axis of length 1 doesn't change the number of elements in the tensor as
# product of components doesn't change when we multiply by one
t = t.reshape(3, 1, 4, 4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

## Each node at the fully connected layer receives the flattened output as input.

1. We need to flatten specific axes within a tensor
2. Whole batch is represented using a single tensor
3. Use stack function to concatenate 3 tensors along a new axis
4. Since, there are 3 tensors along this new axis, Length of this new axis = 3

### First axes has 3 elements, each element is an image

In [34]:
t[0] # first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [35]:
t[0][0] # first color channel in the first image

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [36]:
t[0][0][0] # first row of the pixel in the first color channel of the first image

tensor([1, 1, 1, 1])

In [37]:
t[0][0][0][0] # first pixel value in the first row of the first colot channel of the first image

tensor(1)

In [38]:
# We like to flatten this image. The whole batch is the single tensor that we pass through the CNN. We only want to
# flatten the image tensor within the batch tensor.

# We have flattened the en tire batch.

t.reshape(1, -1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [39]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [40]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [43]:
t.view(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [44]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

## Here we have flattened the entire batch  and that has smashed all images into a single axis.

This flattened batch 

In order to do prediction we need to flatten individual images within color channel still maintaining the batch axes.
That means we need to flatten only part of the tensor.

In [45]:
t.flatten(start_dim = 1).shape # rank 2 tensor

torch.Size([3, 16])

In [47]:
t.flatten(start_dim=1) # flat_dim tells whi ch axes to start with when we flatten, it is second axis, which is
# the color channel axis, but we leave the batch axis intact leaving the shape.

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# Elementwise operations

1. Two elements are corresponding if they occupy the same position in the tensor.
2. Position is determined by indices used to locate the element.
3. two tensors need to have the same shape in order to do elementwise operation
4. It means tensors have the same number of axes and the corresponding axes have the same length
5. Operations mean arithmetic operations using scaler values
6. scaler values are rank 0 tensors, so they have no shape

In [48]:
# 2 axes both have a length of 2 element each, elements of the first axis are array and elements 
# of the second axis are numbers
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)
t2 = torch.tensor([
    [9, 8],
    [7, 6]
], dtype = torch.float32)
t1[0][0], t2[0][0] # corresponding elements of a tensor

(tensor(1.), tensor(9.))

In [49]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [50]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [51]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [52]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [53]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

# Broadcasting

Broadcasting defines how tensors of different shapes are treated  during elementwise operation

In [55]:
import numpy as np
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [56]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [57]:
t1 + torch.tensor(np.broadcast_to(2, t1.shape), dtype=torch.float32)

../torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.


tensor([[3., 4.],
        [5., 6.]])

In [59]:
t1 = torch.tensor([
    [1, 1],
    [1, 1]
], dtype = torch.float32)
t2 = torch.tensor([2, 4], dtype=torch.float32)
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [60]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

# Comparison operation

In [61]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [62]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [63]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [64]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [65]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [66]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [67]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [68]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [69]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [70]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

# Reduction

1. An operation that reduces the number of elements within a single tensor

# Argmax tensor reduction

1. argmax tells us the index location of the maxmimum value of a tensor
2. tensor is reduced a single value indicating the index of the maximum value of the tensoe.

In [74]:
t = torch.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 0]
], dtype=torch.float32)
t.sum() # reduction operation

tensor(8.)

In [75]:
t.numel()

9

In [78]:
t.sum().numel(), t.sum().numel() < t.numel()

(1, True)

In [79]:
t.prod(), t.mean(), t.std()

(tensor(0.), tensor(0.8889), tensor(1.1667))

In [80]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
], dtype=torch.float32)
t.sum(dim=0), t.sum(dim=1)

(tensor([6., 6., 6., 6.]), tensor([ 4.,  8., 12.]))

In [81]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype = torch.float32)

In [82]:
t.max(), t.argmax(), t.flatten()

(tensor(5.),
 tensor(11),
 tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.]))

In [85]:
t.max(dim=0), t.argmax(dim=0)

(torch.return_types.max(
 values=tensor([4., 3., 3., 5.]),
 indices=tensor([2, 1, 1, 2])), tensor([2, 1, 1, 2]))

In [84]:
t.max(dim=1), t.argmax(dim=1)

(torch.return_types.max(
 values=tensor([2., 3., 5.]),
 indices=tensor([3, 2, 3])), tensor([3, 2, 3]))

In [87]:
t = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=torch.float32)
t.mean(), t.mean().item()

(tensor(5.), 5.0)